/*
* Argus Open Source
* Software to apply Statistical Disclosure Control techniques
* 
* Copyright 2014 Statistics Netherlands
* 
* This program is free software; you can redistribute it and/or 
* modify it under the terms of the European Union Public Licence 
* (EUPL) version 1.1, as published by the European Commission.
* 
* You can find the text of the EUPL v1.1 on
* https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
* 
* This software is distributed on an "AS IS" basis without 
* warranties or conditions of any kind, either express or implied.
*/

package tauargus.gui;

import java.awt.Container;
import java.io.File;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.ButtonGroup;
//import javax.swing.JFrame;
import tauargus.model.Application;
//import tauargus.service.TableService;
//import tauargus.utils.ExecUtils;
import argus.utils.SystemUtils;

/**
 *
 * @author Hundepool
 */
public class DialogOptions extends javax.swing.JDialog {
    private javax.swing.JFileChooser fileChooser;
    
    private FrameMain getParentFrame() {
        Container container = this;
        while (!(container instanceof FrameMain)) {
            container = container.getParent();
        }
        return (FrameMain)container;
    }
     /**
     * Creates new form DialogOptions
     */
    public DialogOptions(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null); 
        fileChooser = new javax.swing.JFileChooser();
        jCheckBoxDebugHiTaS.setSelected(Application.SaveDebugHiTaS);
        if (Application.isAnco()) {jLabelAnco.setText("Anco");
                                   jCheckBoxDebugHiTaS.setVisible(true);}
                             else {jLabelAnco.setText("     ");
                                   jCheckBoxDebugHiTaS.setVisible(false);}
        jRadioButtonNoSolver.setVisible(false);
        ButtonGroup bG = new ButtonGroup();
        bG.add(jRadioButtonNoSolver);
        bG.add(jRadioButtonXPress);
        bG.add(jRadioButtonCPlex);
        bG.add(jRadioButtonSCIP);  
        jRadioButtonNoSolver.setVisible(false);
        int i = SystemUtils.getRegInteger("optimal", "maxhitastime", Application.generalMaxHitasTime);
        jTextFieldMaxHitasTime.setText(i+"");
        jTextLogFile.setText(SystemUtils.getRegString("general", "logbook", Application.getTempFile("logbook.txt")));
        jTextCplexLicenseFile.setText(SystemUtils.getRegString("optimal", "cplexlicensefile", "access.ilm"));
        
        i = SystemUtils.getRegInteger("optimal", "solverused", Application.solverSelected);
        switch (i) {
//            case Application.SOLVER_NO: {jRadioButtonNoSolver.setSelected(true); break;}
            case Application.SOLVER_XPRESS : {jRadioButtonXPress.setSelected(true); break;}
            case Application.SOLVER_CPLEX: {jRadioButtonCPlex.setSelected(true); break;}
            case Application.SOLVER_SOPLEX : {jRadioButtonSCIP.setSelected(true); break;}
            default : {jRadioButtonSCIP.setSelected(true);}
        } 
        jLabelCplexLicenseFile.setVisible(jRadioButtonCPlex.isSelected());
        jTextCplexLicenseFile.setVisible(jRadioButtonCPlex.isSelected());
        jButtonCplexLicenseFile.setVisible(jRadioButtonCPlex.isSelected());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        jRadioButtonNoSolver = new javax.swing.JRadioButton();
        jRadioButtonXPress = new javax.swing.JRadioButton();
        jRadioButtonCPlex = new javax.swing.JRadioButton();
        jRadioButtonSCIP = new javax.swing.JRadioButton();
        jLabelAnco = new javax.swing.JLabel();
        jLabelLogFile = new javax.swing.JLabel();
        jTextLogFile = new javax.swing.JTextField();
        jButtonLogFile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldMaxHitasTime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jCheckBoxDebugHiTaS = new javax.swing.JCheckBox();
        jTextCplexLicenseFile = new javax.swing.JTextField();
        jLabelCplexLicenseFile = new javax.swing.JLabel();
        jButtonCplexLicenseFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TauArgus options");
        setModal(true);

        jRadioButtonNoSolver.setText("No solver");
        jRadioButtonNoSolver.setEnabled(false);

        jRadioButtonXPress.setText("Xpress");

        jRadioButtonCPlex.setText("CPlex");
        jRadioButtonCPlex.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonCPlexItemStateChanged(evt);
            }
        });

        jRadioButtonSCIP.setSelected(true);
        jRadioButtonSCIP.setText("Free solver");

        jLabelAnco.setForeground(new java.awt.Color(0, 0, 204));
        jLabelAnco.setText("Anco");
        jLabelAnco.setMaximumSize(new java.awt.Dimension(24, 23));
        jLabelAnco.setMinimumSize(new java.awt.Dimension(24, 23));
        jLabelAnco.setPreferredSize(new java.awt.Dimension(24, 23));
        jLabelAnco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAncoMouseClicked(evt);
            }
        });

        jLabelLogFile.setText("Logfile name:");
        jLabelLogFile.setMaximumSize(new java.awt.Dimension(60, 23));
        jLabelLogFile.setMinimumSize(new java.awt.Dimension(60, 23));
        jLabelLogFile.setPreferredSize(new java.awt.Dimension(60, 23));

        jTextLogFile.setMinimumSize(new java.awt.Dimension(6, 23));
        jTextLogFile.setPreferredSize(new java.awt.Dimension(6, 23));

        jButtonLogFile.setText("...");
        jButtonLogFile.setMaximumSize(new java.awt.Dimension(47, 23));
        jButtonLogFile.setMinimumSize(new java.awt.Dimension(47, 23));
        jButtonLogFile.setPreferredSize(new java.awt.Dimension(47, 23));
        jButtonLogFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogFileActionPerformed(evt);
            }
        });

        jLabel1.setText("Max. time per subtable (modular)");
        jLabel1.setMaximumSize(new java.awt.Dimension(159, 23));
        jLabel1.setMinimumSize(new java.awt.Dimension(159, 23));
        jLabel1.setPreferredSize(new java.awt.Dimension(159, 23));

        jTextFieldMaxHitasTime.setText("10");
        jTextFieldMaxHitasTime.setMinimumSize(new java.awt.Dimension(6, 23));
        jTextFieldMaxHitasTime.setPreferredSize(new java.awt.Dimension(18, 23));

        jLabel2.setText("min");
        jLabel2.setMaximumSize(new java.awt.Dimension(16, 23));
        jLabel2.setMinimumSize(new java.awt.Dimension(16, 23));
        jLabel2.setPreferredSize(new java.awt.Dimension(16, 23));

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jCheckBoxDebugHiTaS.setText("Save debug information (modular/optimal)");

        jTextCplexLicenseFile.setToolTipText("");
        jTextCplexLicenseFile.setMinimumSize(new java.awt.Dimension(6, 23));
        jTextCplexLicenseFile.setName(""); // NOI18N
        jTextCplexLicenseFile.setPreferredSize(new java.awt.Dimension(60, 23));

        jLabelCplexLicenseFile.setText("Licence File:");
        jLabelCplexLicenseFile.setMinimumSize(new java.awt.Dimension(58, 23));
        jLabelCplexLicenseFile.setName(""); // NOI18N
        jLabelCplexLicenseFile.setPreferredSize(new java.awt.Dimension(58, 23));
        jLabelCplexLicenseFile.setRequestFocusEnabled(false);

        jButtonCplexLicenseFile.setText("...");
        jButtonCplexLicenseFile.setMaximumSize(new java.awt.Dimension(47, 23));
        jButtonCplexLicenseFile.setMinimumSize(new java.awt.Dimension(47, 23));
        jButtonCplexLicenseFile.setPreferredSize(new java.awt.Dimension(47, 23));
        jButtonCplexLicenseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCplexLicenseFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonOK))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelLogFile, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextLogFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonXPress, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRadioButtonCPlex, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelCplexLicenseFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextCplexLicenseFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(2, 2, 2)))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCplexLicenseFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonLogFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jTextFieldMaxHitasTime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(jCheckBoxDebugHiTaS))
                                    .addComponent(jRadioButtonSCIP, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonNoSolver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelAnco, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldMaxHitasTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxDebugHiTaS))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextLogFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonLogFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonNoSolver)
                    .addComponent(jLabelAnco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonXPress)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonCPlex)
                        .addComponent(jLabelCplexLicenseFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextCplexLicenseFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonCplexLicenseFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jRadioButtonSCIP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(jButtonOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelAncoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAncoMouseClicked
        // TODO add your handling code here:
        if (jLabelAnco.getText().equals("Anco")) { // Anco options off
            Application.setAnco(false);
            jLabelAnco.setText("      ");
            jCheckBoxDebugHiTaS.setVisible(false);
            jCheckBoxDebugHiTaS.setSelected(false);
            Application.SaveDebugHiTaS = false;
        }
        else{ // Anco options on
            Application.setAnco(true);
            jLabelAnco.setText("Anco");           
            jCheckBoxDebugHiTaS.setVisible(true);
            jCheckBoxDebugHiTaS.setSelected(Application.SaveDebugHiTaS);
        }
        
      FrameMain parent = getParentFrame(); // To have menu items updated when returning to FrameMain
      parent.organise();
    }//GEN-LAST:event_jLabelAncoMouseClicked

    private void jButtonLogFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogFileActionPerformed
        fileChooser.setDialogTitle("Open Logbook file");
        if (jTextLogFile.getText().equals("")){ fileChooser.setSelectedFile(new File(""));}
        else {fileChooser.setSelectedFile(new File(jTextLogFile.getText()));}
        fileChooser.resetChoosableFileFilters();
        fileChooser.setFileFilter(new FileNameExtensionFilter("TauArgus Logfile (*.log)", "log"));
        if (fileChooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            jTextLogFile.setText(fileChooser.getSelectedFile().toString());
            String hs = fileChooser.getSelectedFile().toString();
            
        }
        
               // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogFileActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        int i;
        Application.SaveDebugHiTaS = jCheckBoxDebugHiTaS.isSelected();
        i = Integer.parseInt(jTextFieldMaxHitasTime.getText());
        Application.generalMaxHitasTime = i;
        SystemUtils.putRegInteger("optimal", "maxhitastime", i);

        SystemUtils.putRegBoolean("general", "anco", Application.isAnco());
        SystemUtils.putRegString("optimal", "cplexlicensefile", jTextCplexLicenseFile.getText());
        SystemUtils.putRegString("general", "logbook", jTextLogFile.getText());
        if (!jTextLogFile.getText().equals("")) SystemUtils.setLogbook(jTextLogFile.getText());
          
        i = Application.SOLVER_NO;
        if (jRadioButtonXPress.isSelected()) {i=Application.SOLVER_XPRESS;}
        if (jRadioButtonCPlex.isSelected())  {i=Application.SOLVER_CPLEX;}
        if (jRadioButtonSCIP.isSelected())   {i=Application.SOLVER_SOPLEX;}
        SystemUtils.putRegInteger("optimal", "solverused", i);
        Application.solverSelected = i;
        setVisible(false);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jRadioButtonCPlexItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonCPlexItemStateChanged
        // TODO add your handling code here:
        jLabelCplexLicenseFile.setVisible(jRadioButtonCPlex.isSelected());
        jTextCplexLicenseFile.setVisible(jRadioButtonCPlex.isSelected());
        jButtonCplexLicenseFile.setVisible(jRadioButtonCPlex.isSelected());
    }//GEN-LAST:event_jRadioButtonCPlexItemStateChanged

    private void jButtonCplexLicenseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCplexLicenseFileActionPerformed
        fileChooser.setDialogTitle("Open Cplex License File");
        if (jTextCplexLicenseFile.getText().equals("")){ fileChooser.setSelectedFile(new File(""));}
        else {fileChooser.setSelectedFile(new File(jTextCplexLicenseFile.getText()));}
        fileChooser.resetChoosableFileFilters();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Cplex License File (*.ilm)", "ilm"));
        if (fileChooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            jTextCplexLicenseFile.setText(fileChooser.getSelectedFile().toString());
        }
    }//GEN-LAST:event_jButtonCplexLicenseFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogOptions dialog = new DialogOptions(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCplexLicenseFile;
    private javax.swing.JButton jButtonLogFile;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JCheckBox jCheckBoxDebugHiTaS;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAnco;
    private javax.swing.JLabel jLabelCplexLicenseFile;
    private javax.swing.JLabel jLabelLogFile;
    private javax.swing.JRadioButton jRadioButtonCPlex;
    private javax.swing.JRadioButton jRadioButtonNoSolver;
    private javax.swing.JRadioButton jRadioButtonSCIP;
    private javax.swing.JRadioButton jRadioButtonXPress;
    private javax.swing.JTextField jTextCplexLicenseFile;
    private javax.swing.JTextField jTextFieldMaxHitasTime;
    private javax.swing.JTextField jTextLogFile;
    // End of variables declaration//GEN-END:variables
}
