/*
* Argus Open Source
* Software to apply Statistical Disclosure Control techniques
* 
* Copyright 2014 Statistics Netherlands
* 
* This program is free software; you can redistribute it and/or 
* modify it under the terms of the European Union Public Licence 
* (EUPL) version 1.1, as published by the European Commission.
* 
* You can find the text of the EUPL v1.1 on
* https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
* 
* This software is distributed on an "AS IS" basis without 
* warranties or conditions of any kind, either express or implied.
 */
package tauargus.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import javax.swing.KeyStroke;
import tauargus.model.Application;

/**
 *
 * @author Peter-Paul
 */
public class DialogVersionDetails extends DialogBase {

    /**
     * Creates new form DialogVersionDetails
     */
    public DialogVersionDetails(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        textAreaNames.append("ArgusLib.jar\n");
        textAreaNames.append("TauArgusJava.dll\n");
        textAreaNames.append("TauHitas.dll\n");
        textAreaNames.append("TauRounder.dll");
        
        textAreaVersions.setText("");
        textAreaVersions.append(Application.getArgusLibVersion() + "\n");
        textAreaVersions.append(Application.getArgusJavaVersion() + "\n");
        textAreaVersions.append(Application.getHitasVersion() + "\n");
        textAreaVersions.append(Application.getRounderVersion());
        
        labelArgusVersion.setText(Application.getFullVersion() + " build " + Application.BUILD);
                
        ActionListener actionListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                setVisible(false);
                dispose();
            }
        };
        KeyStroke stroke;
        stroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        stroke = KeyStroke.getKeyStroke(KeyEvent.VK_C, InputEvent.ALT_DOWN_MASK);

        setLocationRelativeTo(parent);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textAreaNames = new javax.swing.JTextArea();
        textAreaVersions = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelArgusVersion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(null);
        setIconImages(null);
        setResizable(false);

        textAreaNames.setEditable(false);
        textAreaNames.setBackground(new java.awt.Color(240, 240, 240));
        textAreaNames.setColumns(20);
        textAreaNames.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textAreaNames.setRows(8);
        textAreaNames.setFocusable(false);
        textAreaNames.setHighlighter(null);
        textAreaNames.setMinimumSize(new java.awt.Dimension(102, 130));
        textAreaNames.setPreferredSize(new java.awt.Dimension(102, 130));

        textAreaVersions.setEditable(false);
        textAreaVersions.setBackground(new java.awt.Color(240, 240, 240));
        textAreaVersions.setColumns(20);
        textAreaVersions.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textAreaVersions.setRows(5);
        textAreaVersions.setText("4.0.2 build 1\n1.1.4.3\n4.2.4.0\n1.2.1.0");
        textAreaVersions.setFocusable(false);
        textAreaVersions.setHighlighter(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tauargus/resources/Tau32.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html> &tau;-ARGUS");

        labelArgusVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelArgusVersion.setText("5.0.0 build 99");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelArgusVersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(textAreaNames, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(89, 89, 89)))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(textAreaVersions, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelArgusVersion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAreaNames, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAreaVersions, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelArgusVersion;
    private javax.swing.JTextArea textAreaNames;
    private javax.swing.JTextArea textAreaVersions;
    // End of variables declaration//GEN-END:variables
}
