/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tauargus.gui;

import argus.utils.SystemUtils;
import java.io.File;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tauargus.model.ArgusException;
import tauargus.model.TableSet;
import tauargus.utils.TauArgusUtils;

/**
 *
 * @author pwof
 */
public class DialogChangePTable extends DialogBase{ //javax.swing.JDialog {

    private static final Logger logger = Logger.getLogger(DialogOpenMicrodata.class.getName());
    
    public static final int CANCEL_OPTION = 1;
    public static final int APPROVE_OPTION = 0;
    
    private int returnValue = CANCEL_OPTION;
    private TableSet tmpTableSet;
    
    /**
     * Creates new form DialogChangePTable
     */
    public DialogChangePTable(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }
    
    public int showDialog(TableSet tableSet){
        tmpTableSet=tableSet;
        
        try{ 
            String hs = tmpTableSet.cellkeyVar.PTableFile;
            if ( hs.indexOf("\\",0)>0 ||hs.indexOf(":",0)>0||hs.indexOf(":",0)>0){}
            else { hs = tmpTableSet.cellkeyVar.metadata.getFilePath(tmpTableSet.cellkeyVar.PTableFile);}
            textFieldPTable.setText(hs);
        
            hs = tmpTableSet.cellkeyVar.PTableFileCont;
            if ( hs.indexOf("\\",0)>0 ||hs.indexOf(":",0)>0||hs.indexOf(":",0)>0){}
            else { hs = tmpTableSet.cellkeyVar.metadata.getFilePath(tmpTableSet.cellkeyVar.PTableFileCont);}
            textFieldPTableCont.setText(hs);
        
            hs = tmpTableSet.cellkeyVar.PTableFileSep;
            if ( hs.indexOf("\\",0)>0 ||hs.indexOf(":",0)>0||hs.indexOf(":",0)>0){}
            else { hs = tmpTableSet.cellkeyVar.metadata.getFilePath(tmpTableSet.cellkeyVar.PTableFileSep);}
            textFieldPTableSep.setText(hs);
        
            jLabelpTableCont.setVisible(tmpTableSet.respVar.isResponse());
            jLabelpTableSep.setVisible(tmpTableSet.respVar.isResponse() && tmpTableSet.respVar.CKMseparation);
            textFieldPTableCont.setVisible(tmpTableSet.respVar.isResponse());
            textFieldPTableSep.setVisible(tmpTableSet.respVar.isResponse() && tmpTableSet.respVar.CKMseparation);
        }
        catch (ArgusException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        setVisible(true);
        return returnValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filechooser = new javax.swing.JFileChooser();
        jLabelpTable = new javax.swing.JLabel();
        textFieldPTable = new javax.swing.JTextField();
        buttonPTable = new javax.swing.JButton();
        buttonOK = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        jLabelpTableCont = new javax.swing.JLabel();
        jLabelpTableSep = new javax.swing.JLabel();
        textFieldPTableCont = new javax.swing.JTextField();
        textFieldPTableSep = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                DialogClosing(evt);
            }
        });

        jLabelpTable.setText("FREQ ptable file:");

        buttonPTable.setText("...");
        buttonPTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPTableActionPerformed(evt);
            }
        });

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        jLabelpTableCont.setText("CONT ptable file:");

        jLabelpTableSep.setText("SEP ptable file:");

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelpTableSep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelpTableCont, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelpTable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldPTable)
                            .addComponent(textFieldPTableCont, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                            .addComponent(textFieldPTableSep))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonPTable, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelpTable)
                    .addComponent(textFieldPTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPTable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelpTableCont)
                    .addComponent(textFieldPTableCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelpTableSep)
                    .addComponent(textFieldPTableSep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOK)
                    .addComponent(buttonCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        returnValue = CANCEL_OPTION;
        setVisible(false);
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        if (textFieldPTable.getText().trim().equals("")) 
        {
            JOptionPane.showMessageDialog(this,"Please specify ptable file.");
            return;
        }
        if (!TauArgusUtils.ExistFile(textFieldPTable.getText()))
        {
            JOptionPane.showMessageDialog(this,"Ptable file "+textFieldPTable.getText()+" does not exist.");
            return;
        }
        SystemUtils.writeLogbook("Ptable file: "+textFieldPTable.getText()+" will be used when applying CKM.");
        
        returnValue = APPROVE_OPTION;
        setVisible(false);
    }//GEN-LAST:event_buttonOKActionPerformed

    private void buttonPTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPTableActionPerformed
        TauArgusUtils.getDataDirFromRegistry(filechooser);
        filechooser.setDialogTitle("Select ptable file for frequency variable");
        filechooser.setSelectedFile(new File(""));
        filechooser.resetChoosableFileFilters();
        if (filechooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            String hs = filechooser.getSelectedFile().toString();
            textFieldPTable.setText(hs);
            TauArgusUtils.putDataDirInRegistry(hs);
            tmpTableSet.cellkeyVar.PTableFile=hs;
        }
    }//GEN-LAST:event_buttonPTableActionPerformed

    private void DialogClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_DialogClosing
        setVisible(false);
    }//GEN-LAST:event_DialogClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TauArgusUtils.getDataDirFromRegistry(filechooser);
        filechooser.setDialogTitle("Select ptable file for continuous variable");
        filechooser.setSelectedFile(new File(""));
        filechooser.resetChoosableFileFilters();
        if (filechooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            String hs = filechooser.getSelectedFile().toString();
            textFieldPTableCont.setText(hs);
            TauArgusUtils.putDataDirInRegistry(hs);
            tmpTableSet.cellkeyVar.PTableFileCont=hs;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TauArgusUtils.getDataDirFromRegistry(filechooser);
        filechooser.setDialogTitle("Select ptable file for continuous variable, small values");
        filechooser.setSelectedFile(new File(""));
        filechooser.resetChoosableFileFilters();
        if (filechooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            String hs = filechooser.getSelectedFile().toString();
            textFieldPTableSep.setText(hs);
            TauArgusUtils.putDataDirInRegistry(hs);
            tmpTableSet.cellkeyVar.PTableFileSep=hs;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogChangePTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogChangePTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogChangePTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogChangePTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogChangePTable dialog = new DialogChangePTable(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton buttonPTable;
    private javax.swing.JFileChooser filechooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelpTable;
    private javax.swing.JLabel jLabelpTableCont;
    private javax.swing.JLabel jLabelpTableSep;
    private javax.swing.JTextField textFieldPTable;
    private javax.swing.JTextField textFieldPTableCont;
    private javax.swing.JTextField textFieldPTableSep;
    // End of variables declaration//GEN-END:variables
}
