/*
* Argus Open Source
* Software to apply Statistical Disclosure Control techniques
* 
* Copyright 2014 Statistics Netherlands
* 
* This program is free software; you can redistribute it and/or 
* modify it under the terms of the European Union Public Licence 
* (EUPL) version 1.1, as published by the European Commission.
* 
* You can find the text of the EUPL v1.1 on
* https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
* 
* This software is distributed on an "AS IS" basis without 
* warranties or conditions of any kind, either express or implied.
*/

package tauargus.gui;

import argus.model.ArgusException;
import argus.utils.SystemUtils;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.filechooser.FileNameExtensionFilter;
import tauargus.model.Application;
import tauargus.resources.ContextHelp;
import tauargus.utils.TauArgusUtils;

/**
 *
 * @author Statistics Netherlands
 *
 */
public class DialogBase extends javax.swing.JDialog {

    /*
     * Makes it possible to use <ESC> to close the Dialog (cancel)
     */
    @Override
    protected JRootPane createRootPane() {
        ActionListener actionListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                setVisible(false);
                dispose();
            }
        };    
 
        KeyStroke stroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        JRootPane rootPane = new JRootPane();
        rootPane.registerKeyboardAction(actionListener, stroke, JComponent.WHEN_IN_FOCUSED_WINDOW);
        return rootPane;
    }
    
    /**
     * Creates new form DialogBase
     * @param parent the Frame of the mainFrame.
     * @param modal boolean to set the modal status
     * @param controller the controller of the view.
     */
    public DialogBase(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setHelpAction();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * 
     * @param title
     * @param forSaving
     * @param filter
     * @return 
     */
    public String showFileDialog(String title, boolean forSaving, String[] filter) {
        JFileChooser fileChooser = new JFileChooser();
        TauArgusUtils.getDataDirFromRegistry(fileChooser);
        fileChooser.setDialogTitle(title);
        fileChooser.resetChoosableFileFilters();
        String[] firstFilter = splitFilter(filter[0]);
        fileChooser.setFileFilter(new FileNameExtensionFilter(firstFilter[0], firstFilter[1]));
        for (int index=1; index < filter.length; index++) {
            String[] otherFilter = splitFilter(filter[index]);
            fileChooser.addChoosableFileFilter(new FileNameExtensionFilter(otherFilter[0], otherFilter[1]));
        }
        int result = forSaving ? fileChooser.showSaveDialog(this) : fileChooser.showOpenDialog(this);
        if (result != JFileChooser.APPROVE_OPTION) {
            return null;
        }
        String hs = fileChooser.getSelectedFile().getParent();
        if (!"".equals(hs)){
            SystemUtils.putRegString("general", "datadir", hs);
        }
        return fileChooser.getSelectedFile().getPath();
    } 
    
    /**
     * 
     * @param filter
     * @return 
     */
    private String[] splitFilter(String filter) {
        return filter.split("\\|");
    }
    
    private void setHelpAction() {
        
        Action action = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showHelp();
            }
        };
        this.rootPane.getActionMap().put("f1action", action);
        this.rootPane.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(
                KeyStroke.getKeyStroke("F1"), "f1action");
    }

    protected String getHelpNamedDestination() {
        return ContextHelp.fromClassName(this.getClass().getName());
    }
    
    private void showHelp() {
        try{
        Application.showHelp(getHelpNamedDestination());
        }
        catch (ArgusException ex){JOptionPane.showMessageDialog(null, ex.getMessage());}
    }

    /**
     * 
     * @param stepName 
     */
    public void showStepName(String stepName) {
        //Base class implementation is empty
    }

    /**
     * 
     * @param progress 
     */
    public void setProgress(int progress) {
        //Base class implementation is empty
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
